spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: P@ssw0rd_123
    url: jdbc:postgresql://localhost:5432/fullstack
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true